package com.pro.test.web.dao;

import com.pro.test.web.entity.TbHxpUserLogin;
import com.pro.test.web.entity.TbHxpUserLoginExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TbHxpUserLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    int countByExample(TbHxpUserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    int deleteByExample(TbHxpUserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_hxp_user_login",
        "where id = #{id,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_hxp_user_login (id, login_name, ",
        "login_password, user_id, ",
        "login_count, is_locked, ",
        "unlocked_date, ip_address, ",
        "last_login_time, status)",
        "values (#{id,jdbcType=CHAR}, #{loginName,jdbcType=VARCHAR}, ",
        "#{loginPassword,jdbcType=VARCHAR}, #{userId,jdbcType=CHAR}, ",
        "#{loginCount,jdbcType=INTEGER}, #{isLocked,jdbcType=INTEGER}, ",
        "#{unlockedDate,jdbcType=DATE}, #{ipAddress,jdbcType=CHAR}, ",
        "#{lastLoginTime,jdbcType=DATE}, #{status,jdbcType=INTEGER})"
    })
    int insert(TbHxpUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    int insertSelective(TbHxpUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    List<TbHxpUserLogin> selectByExample(TbHxpUserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, login_name, login_password, user_id, login_count, is_locked, unlocked_date, ",
        "ip_address, last_login_time, status",
        "from tb_hxp_user_login",
        "where id = #{id,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbHxpUserLogin selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbHxpUserLogin record, @Param("example") TbHxpUserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbHxpUserLogin record, @Param("example") TbHxpUserLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbHxpUserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_user_login",
        "set login_name = #{loginName,jdbcType=VARCHAR},",
          "login_password = #{loginPassword,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=CHAR},",
          "login_count = #{loginCount,jdbcType=INTEGER},",
          "is_locked = #{isLocked,jdbcType=INTEGER},",
          "unlocked_date = #{unlockedDate,jdbcType=DATE},",
          "ip_address = #{ipAddress,jdbcType=CHAR},",
          "last_login_time = #{lastLoginTime,jdbcType=DATE},",
          "status = #{status,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbHxpUserLogin record);
}