package com.pro.test.web.dao;

import com.pro.test.web.entity.TbHxpComment;
import com.pro.test.web.entity.TbHxpCommentExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TbHxpCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    int countByExample(TbHxpCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    int deleteByExample(TbHxpCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_hxp_comment",
        "where comment_id = #{commentId,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_hxp_comment (comment_id, article_id, ",
        "comment_context, user_id, ",
        "user_name, user_head_portrait, ",
        "comment_ip, comment_likes, ",
        "create_date)",
        "values (#{commentId,jdbcType=CHAR}, #{articleId,jdbcType=CHAR}, ",
        "#{commentContext,jdbcType=VARCHAR}, #{userId,jdbcType=CHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{userHeadPortrait,jdbcType=VARCHAR}, ",
        "#{commentIp,jdbcType=VARCHAR}, #{commentLikes,jdbcType=INTEGER}, ",
        "#{createDate,jdbcType=DATE})"
    })
    int insert(TbHxpComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    int insertSelective(TbHxpComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    List<TbHxpComment> selectByExample(TbHxpCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "comment_id, article_id, comment_context, user_id, user_name, user_head_portrait, ",
        "comment_ip, comment_likes, create_date",
        "from tb_hxp_comment",
        "where comment_id = #{commentId,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbHxpComment selectByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbHxpComment record, @Param("example") TbHxpCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbHxpComment record, @Param("example") TbHxpCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbHxpComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_comment",
        "set article_id = #{articleId,jdbcType=CHAR},",
          "comment_context = #{commentContext,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=CHAR},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "user_head_portrait = #{userHeadPortrait,jdbcType=VARCHAR},",
          "comment_ip = #{commentIp,jdbcType=VARCHAR},",
          "comment_likes = #{commentLikes,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=DATE}",
        "where comment_id = #{commentId,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbHxpComment record);
}