package com.pro.test.web.dao;

import com.pro.test.web.entity.TbHxpArticle;
import com.pro.test.web.entity.TbHxpArticleExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;


@Component
public interface TbHxpArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    int countByExample(TbHxpArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    int deleteByExample(TbHxpArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_hxp_article",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_hxp_article (article_id, article_title, ",
        "article_introduced, article_author_id, ",
        "article_author_name, article_tags, ",
        "last_comment_date, comment_count, ",
        "likes_count, read_count, ",
        "is_open, on_top, article_floor, ",
        "author_support, key_words, ",
        "is_content_finish, create_date, ",
        "create_by, update_date, ",
        "update_by, remark)",
        "values (#{articleId,jdbcType=CHAR}, #{articleTitle,jdbcType=VARCHAR}, ",
        "#{articleIntroduced,jdbcType=VARCHAR}, #{articleAuthorId,jdbcType=CHAR}, ",
        "#{articleAuthorName,jdbcType=VARCHAR}, #{articleTags,jdbcType=VARCHAR}, ",
        "#{lastCommentDate,jdbcType=DATE}, #{commentCount,jdbcType=INTEGER}, ",
        "#{likesCount,jdbcType=INTEGER}, #{readCount,jdbcType=INTEGER}, ",
        "#{isOpen,jdbcType=INTEGER}, #{onTop,jdbcType=INTEGER}, #{articleFloor,jdbcType=INTEGER}, ",
        "#{authorSupport,jdbcType=INTEGER}, #{keyWords,jdbcType=VARCHAR}, ",
        "#{isContentFinish,jdbcType=INTEGER}, #{createDate,jdbcType=DATE}, ",
        "#{createBy,jdbcType=CHAR}, #{updateDate,jdbcType=DATE}, ",
        "#{updateBy,jdbcType=CHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(TbHxpArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    int insertSelective(TbHxpArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    List<TbHxpArticle> selectByExample(TbHxpArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "article_id, article_title, article_introduced, article_author_id, article_author_name, ",
        "article_tags, last_comment_date, comment_count, likes_count, read_count, is_open, ",
        "on_top, article_floor, author_support, key_words, is_content_finish, create_date, ",
        "create_by, update_date, update_by, remark",
        "from tb_hxp_article",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbHxpArticle selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbHxpArticle record, @Param("example") TbHxpArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbHxpArticle record, @Param("example") TbHxpArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbHxpArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_article",
        "set article_title = #{articleTitle,jdbcType=VARCHAR},",
          "article_introduced = #{articleIntroduced,jdbcType=VARCHAR},",
          "article_author_id = #{articleAuthorId,jdbcType=CHAR},",
          "article_author_name = #{articleAuthorName,jdbcType=VARCHAR},",
          "article_tags = #{articleTags,jdbcType=VARCHAR},",
          "last_comment_date = #{lastCommentDate,jdbcType=DATE},",
          "comment_count = #{commentCount,jdbcType=INTEGER},",
          "likes_count = #{likesCount,jdbcType=INTEGER},",
          "read_count = #{readCount,jdbcType=INTEGER},",
          "is_open = #{isOpen,jdbcType=INTEGER},",
          "on_top = #{onTop,jdbcType=INTEGER},",
          "article_floor = #{articleFloor,jdbcType=INTEGER},",
          "author_support = #{authorSupport,jdbcType=INTEGER},",
          "key_words = #{keyWords,jdbcType=VARCHAR},",
          "is_content_finish = #{isContentFinish,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=DATE},",
          "create_by = #{createBy,jdbcType=CHAR},",
          "update_date = #{updateDate,jdbcType=DATE},",
          "update_by = #{updateBy,jdbcType=CHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbHxpArticle record);
}