package com.pro.test.web.dao;

import com.pro.test.web.entity.TbHxpTags;
import com.pro.test.web.entity.TbHxpTagsExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TbHxpTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    int countByExample(TbHxpTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    int deleteByExample(TbHxpTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_hxp_tags",
        "where tag_id = #{tagId,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_hxp_tags (tag_id, tag_name, ",
        "tag_title, tag_img, ",
        "tag_count, create_date, ",
        "create_by, update_date, ",
        "update_by, remark)",
        "values (#{tagId,jdbcType=CHAR}, #{tagName,jdbcType=VARCHAR}, ",
        "#{tagTitle,jdbcType=VARCHAR}, #{tagImg,jdbcType=VARCHAR}, ",
        "#{tagCount,jdbcType=INTEGER}, #{createDate,jdbcType=DATE}, ",
        "#{createBy,jdbcType=CHAR}, #{updateDate,jdbcType=DATE}, ",
        "#{updateBy,jdbcType=CHAR}, #{remark,jdbcType=VARCHAR})"
    })
    int insert(TbHxpTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    int insertSelective(TbHxpTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    List<TbHxpTags> selectByExample(TbHxpTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "tag_id, tag_name, tag_title, tag_img, tag_count, create_date, create_by, update_date, ",
        "update_by, remark",
        "from tb_hxp_tags",
        "where tag_id = #{tagId,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbHxpTags selectByPrimaryKey(String tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbHxpTags record, @Param("example") TbHxpTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbHxpTags record, @Param("example") TbHxpTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbHxpTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_tags",
        "set tag_name = #{tagName,jdbcType=VARCHAR},",
          "tag_title = #{tagTitle,jdbcType=VARCHAR},",
          "tag_img = #{tagImg,jdbcType=VARCHAR},",
          "tag_count = #{tagCount,jdbcType=INTEGER},",
          "create_date = #{createDate,jdbcType=DATE},",
          "create_by = #{createBy,jdbcType=CHAR},",
          "update_date = #{updateDate,jdbcType=DATE},",
          "update_by = #{updateBy,jdbcType=CHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where tag_id = #{tagId,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbHxpTags record);
}