package com.pro.test.web.dao;

import com.pro.test.web.entity.TbHxpArticleContent;
import com.pro.test.web.entity.TbHxpArticleContentExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TbHxpArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int countByExample(TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int deleteByExample(TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_hxp_article_content",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_hxp_article_content (article_id, create_date, ",
        "create_by, update_date, ",
        "update_by, article_content)",
        "values (#{articleId,jdbcType=CHAR}, #{createDate,jdbcType=DATE}, ",
        "#{createBy,jdbcType=CHAR}, #{updateDate,jdbcType=DATE}, ",
        "#{updateBy,jdbcType=CHAR}, #{articleContent,jdbcType=LONGVARCHAR})"
    })
    int insert(TbHxpArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int insertSelective(TbHxpArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    List<TbHxpArticleContent> selectByExampleWithBLOBs(TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    List<TbHxpArticleContent> selectByExample(TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "article_id, create_date, create_by, update_date, update_by, article_content",
        "from tb_hxp_article_content",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    @ResultMap("ResultMapWithBLOBs")
    TbHxpArticleContent selectByPrimaryKey(String articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbHxpArticleContent record, @Param("example") TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") TbHxpArticleContent record, @Param("example") TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbHxpArticleContent record, @Param("example") TbHxpArticleContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbHxpArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_article_content",
        "set create_date = #{createDate,jdbcType=DATE},",
          "create_by = #{createBy,jdbcType=CHAR},",
          "update_date = #{updateDate,jdbcType=DATE},",
          "update_by = #{updateBy,jdbcType=CHAR},",
          "article_content = #{articleContent,jdbcType=LONGVARCHAR}",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    int updateByPrimaryKeyWithBLOBs(TbHxpArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_article_content",
        "set create_date = #{createDate,jdbcType=DATE},",
          "create_by = #{createBy,jdbcType=CHAR},",
          "update_date = #{updateDate,jdbcType=DATE},",
          "update_by = #{updateBy,jdbcType=CHAR}",
        "where article_id = #{articleId,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbHxpArticleContent record);
}