package com.pro.test.web.dao;

import com.pro.test.web.entity.TbHxpUser;
import com.pro.test.web.entity.TbHxpUserExample;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface TbHxpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    int countByExample(TbHxpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    int deleteByExample(TbHxpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_hxp_user",
        "where user_id = #{userId,jdbcType=CHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_hxp_user (user_id, user_name, ",
        "publish_count, comments_count, ",
        "like_tags)",
        "values (#{userId,jdbcType=CHAR}, #{userName,jdbcType=VARCHAR}, ",
        "#{publishCount,jdbcType=INTEGER}, #{commentsCount,jdbcType=INTEGER}, ",
        "#{likeTags,jdbcType=VARCHAR})"
    })
    int insert(TbHxpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    int insertSelective(TbHxpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    List<TbHxpUser> selectByExample(TbHxpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "user_id, user_name, publish_count, comments_count, like_tags",
        "from tb_hxp_user",
        "where user_id = #{userId,jdbcType=CHAR}"
    })
    @ResultMap("BaseResultMap")
    TbHxpUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbHxpUser record, @Param("example") TbHxpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbHxpUser record, @Param("example") TbHxpUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbHxpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    @Update({
        "update tb_hxp_user",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "publish_count = #{publishCount,jdbcType=INTEGER},",
          "comments_count = #{commentsCount,jdbcType=INTEGER},",
          "like_tags = #{likeTags,jdbcType=VARCHAR}",
        "where user_id = #{userId,jdbcType=CHAR}"
    })
    int updateByPrimaryKey(TbHxpUser record);
}