package com.pro.test.web.entity;

import java.util.Date;

public class TbHxpComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.comment_id
     *
     * @mbggenerated
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.comment_context
     *
     * @mbggenerated
     */
    private String commentContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.user_head_portrait
     *
     * @mbggenerated
     */
    private String userHeadPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.comment_ip
     *
     * @mbggenerated
     */
    private String commentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.comment_likes
     *
     * @mbggenerated
     */
    private Integer commentLikes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_comment.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_comment
     *
     * @mbggenerated
     */
    public TbHxpComment(String commentId, String articleId, String commentContext, String userId, String userName, String userHeadPortrait, String commentIp, Integer commentLikes, Date createDate) {
        this.commentId = commentId;
        this.articleId = articleId;
        this.commentContext = commentContext;
        this.userId = userId;
        this.userName = userName;
        this.userHeadPortrait = userHeadPortrait;
        this.commentIp = commentIp;
        this.commentLikes = commentLikes;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.comment_id
     *
     * @return the value of tb_hxp_comment.comment_id
     *
     * @mbggenerated
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.article_id
     *
     * @return the value of tb_hxp_comment.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.comment_context
     *
     * @return the value of tb_hxp_comment.comment_context
     *
     * @mbggenerated
     */
    public String getCommentContext() {
        return commentContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.user_id
     *
     * @return the value of tb_hxp_comment.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.user_name
     *
     * @return the value of tb_hxp_comment.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.user_head_portrait
     *
     * @return the value of tb_hxp_comment.user_head_portrait
     *
     * @mbggenerated
     */
    public String getUserHeadPortrait() {
        return userHeadPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.comment_ip
     *
     * @return the value of tb_hxp_comment.comment_ip
     *
     * @mbggenerated
     */
    public String getCommentIp() {
        return commentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.comment_likes
     *
     * @return the value of tb_hxp_comment.comment_likes
     *
     * @mbggenerated
     */
    public Integer getCommentLikes() {
        return commentLikes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_comment.create_date
     *
     * @return the value of tb_hxp_comment.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }
}