package com.pro.test.web.entity;

public class TbHxpUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user.publish_count
     *
     * @mbggenerated
     */
    private Integer publishCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user.comments_count
     *
     * @mbggenerated
     */
    private Integer commentsCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user.like_tags
     *
     * @mbggenerated
     */
    private String likeTags;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user
     *
     * @mbggenerated
     */
    public TbHxpUser(String userId, String userName, Integer publishCount, Integer commentsCount, String likeTags) {
        this.userId = userId;
        this.userName = userName;
        this.publishCount = publishCount;
        this.commentsCount = commentsCount;
        this.likeTags = likeTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user.user_id
     *
     * @return the value of tb_hxp_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user.user_name
     *
     * @return the value of tb_hxp_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user.publish_count
     *
     * @return the value of tb_hxp_user.publish_count
     *
     * @mbggenerated
     */
    public Integer getPublishCount() {
        return publishCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user.comments_count
     *
     * @return the value of tb_hxp_user.comments_count
     *
     * @mbggenerated
     */
    public Integer getCommentsCount() {
        return commentsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user.like_tags
     *
     * @return the value of tb_hxp_user.like_tags
     *
     * @mbggenerated
     */
    public String getLikeTags() {
        return likeTags;
    }
}