package com.pro.test.web.entity;

import java.util.Date;

public class TbHxpTags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.tag_id
     *
     * @mbggenerated
     */
    private String tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.tag_name
     *
     * @mbggenerated
     */
    private String tagName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.tag_title
     *
     * @mbggenerated
     */
    private String tagTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.tag_img
     *
     * @mbggenerated
     */
    private String tagImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.tag_count
     *
     * @mbggenerated
     */
    private Integer tagCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_tags.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_tags
     *
     * @mbggenerated
     */
    public TbHxpTags(String tagId, String tagName, String tagTitle, String tagImg, Integer tagCount, Date createDate, String createBy, Date updateDate, String updateBy, String remark) {
        this.tagId = tagId;
        this.tagName = tagName;
        this.tagTitle = tagTitle;
        this.tagImg = tagImg;
        this.tagCount = tagCount;
        this.createDate = createDate;
        this.createBy = createBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.tag_id
     *
     * @return the value of tb_hxp_tags.tag_id
     *
     * @mbggenerated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.tag_name
     *
     * @return the value of tb_hxp_tags.tag_name
     *
     * @mbggenerated
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.tag_title
     *
     * @return the value of tb_hxp_tags.tag_title
     *
     * @mbggenerated
     */
    public String getTagTitle() {
        return tagTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.tag_img
     *
     * @return the value of tb_hxp_tags.tag_img
     *
     * @mbggenerated
     */
    public String getTagImg() {
        return tagImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.tag_count
     *
     * @return the value of tb_hxp_tags.tag_count
     *
     * @mbggenerated
     */
    public Integer getTagCount() {
        return tagCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.create_date
     *
     * @return the value of tb_hxp_tags.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.create_by
     *
     * @return the value of tb_hxp_tags.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.update_date
     *
     * @return the value of tb_hxp_tags.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.update_by
     *
     * @return the value of tb_hxp_tags.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_tags.remark
     *
     * @return the value of tb_hxp_tags.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }
}