package com.pro.test.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbHxpArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public TbHxpArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("article_id is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("article_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(String value) {
            addCriterion("article_id =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(String value) {
            addCriterion("article_id <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(String value) {
            addCriterion("article_id >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(String value) {
            addCriterion("article_id >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(String value) {
            addCriterion("article_id <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(String value) {
            addCriterion("article_id <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLike(String value) {
            addCriterion("article_id like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotLike(String value) {
            addCriterion("article_id not like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<String> values) {
            addCriterion("article_id in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<String> values) {
            addCriterion("article_id not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(String value1, String value2) {
            addCriterion("article_id between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(String value1, String value2) {
            addCriterion("article_id not between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNull() {
            addCriterion("article_title is null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNotNull() {
            addCriterion("article_title is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleEqualTo(String value) {
            addCriterion("article_title =", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotEqualTo(String value) {
            addCriterion("article_title <>", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThan(String value) {
            addCriterion("article_title >", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThanOrEqualTo(String value) {
            addCriterion("article_title >=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThan(String value) {
            addCriterion("article_title <", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThanOrEqualTo(String value) {
            addCriterion("article_title <=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLike(String value) {
            addCriterion("article_title like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotLike(String value) {
            addCriterion("article_title not like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIn(List<String> values) {
            addCriterion("article_title in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotIn(List<String> values) {
            addCriterion("article_title not in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleBetween(String value1, String value2) {
            addCriterion("article_title between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotBetween(String value1, String value2) {
            addCriterion("article_title not between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedIsNull() {
            addCriterion("article_introduced is null");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedIsNotNull() {
            addCriterion("article_introduced is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedEqualTo(String value) {
            addCriterion("article_introduced =", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedNotEqualTo(String value) {
            addCriterion("article_introduced <>", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedGreaterThan(String value) {
            addCriterion("article_introduced >", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedGreaterThanOrEqualTo(String value) {
            addCriterion("article_introduced >=", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedLessThan(String value) {
            addCriterion("article_introduced <", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedLessThanOrEqualTo(String value) {
            addCriterion("article_introduced <=", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedLike(String value) {
            addCriterion("article_introduced like", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedNotLike(String value) {
            addCriterion("article_introduced not like", value, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedIn(List<String> values) {
            addCriterion("article_introduced in", values, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedNotIn(List<String> values) {
            addCriterion("article_introduced not in", values, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedBetween(String value1, String value2) {
            addCriterion("article_introduced between", value1, value2, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleIntroducedNotBetween(String value1, String value2) {
            addCriterion("article_introduced not between", value1, value2, "articleIntroduced");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdIsNull() {
            addCriterion("article_author_id is null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdIsNotNull() {
            addCriterion("article_author_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdEqualTo(String value) {
            addCriterion("article_author_id =", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotEqualTo(String value) {
            addCriterion("article_author_id <>", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdGreaterThan(String value) {
            addCriterion("article_author_id >", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdGreaterThanOrEqualTo(String value) {
            addCriterion("article_author_id >=", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdLessThan(String value) {
            addCriterion("article_author_id <", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdLessThanOrEqualTo(String value) {
            addCriterion("article_author_id <=", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdLike(String value) {
            addCriterion("article_author_id like", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotLike(String value) {
            addCriterion("article_author_id not like", value, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdIn(List<String> values) {
            addCriterion("article_author_id in", values, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotIn(List<String> values) {
            addCriterion("article_author_id not in", values, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdBetween(String value1, String value2) {
            addCriterion("article_author_id between", value1, value2, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorIdNotBetween(String value1, String value2) {
            addCriterion("article_author_id not between", value1, value2, "articleAuthorId");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameIsNull() {
            addCriterion("article_author_name is null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameIsNotNull() {
            addCriterion("article_author_name is not null");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameEqualTo(String value) {
            addCriterion("article_author_name =", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameNotEqualTo(String value) {
            addCriterion("article_author_name <>", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameGreaterThan(String value) {
            addCriterion("article_author_name >", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameGreaterThanOrEqualTo(String value) {
            addCriterion("article_author_name >=", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameLessThan(String value) {
            addCriterion("article_author_name <", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameLessThanOrEqualTo(String value) {
            addCriterion("article_author_name <=", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameLike(String value) {
            addCriterion("article_author_name like", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameNotLike(String value) {
            addCriterion("article_author_name not like", value, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameIn(List<String> values) {
            addCriterion("article_author_name in", values, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameNotIn(List<String> values) {
            addCriterion("article_author_name not in", values, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameBetween(String value1, String value2) {
            addCriterion("article_author_name between", value1, value2, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleAuthorNameNotBetween(String value1, String value2) {
            addCriterion("article_author_name not between", value1, value2, "articleAuthorName");
            return (Criteria) this;
        }

        public Criteria andArticleTagsIsNull() {
            addCriterion("article_tags is null");
            return (Criteria) this;
        }

        public Criteria andArticleTagsIsNotNull() {
            addCriterion("article_tags is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTagsEqualTo(String value) {
            addCriterion("article_tags =", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsNotEqualTo(String value) {
            addCriterion("article_tags <>", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsGreaterThan(String value) {
            addCriterion("article_tags >", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsGreaterThanOrEqualTo(String value) {
            addCriterion("article_tags >=", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsLessThan(String value) {
            addCriterion("article_tags <", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsLessThanOrEqualTo(String value) {
            addCriterion("article_tags <=", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsLike(String value) {
            addCriterion("article_tags like", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsNotLike(String value) {
            addCriterion("article_tags not like", value, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsIn(List<String> values) {
            addCriterion("article_tags in", values, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsNotIn(List<String> values) {
            addCriterion("article_tags not in", values, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsBetween(String value1, String value2) {
            addCriterion("article_tags between", value1, value2, "articleTags");
            return (Criteria) this;
        }

        public Criteria andArticleTagsNotBetween(String value1, String value2) {
            addCriterion("article_tags not between", value1, value2, "articleTags");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateIsNull() {
            addCriterion("last_comment_date is null");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateIsNotNull() {
            addCriterion("last_comment_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateEqualTo(Date value) {
            addCriterionForJDBCDate("last_comment_date =", value, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("last_comment_date <>", value, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateGreaterThan(Date value) {
            addCriterionForJDBCDate("last_comment_date >", value, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_comment_date >=", value, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateLessThan(Date value) {
            addCriterionForJDBCDate("last_comment_date <", value, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("last_comment_date <=", value, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateIn(List<Date> values) {
            addCriterionForJDBCDate("last_comment_date in", values, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("last_comment_date not in", values, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_comment_date between", value1, value2, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andLastCommentDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("last_comment_date not between", value1, value2, "lastCommentDate");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountIsNull() {
            addCriterion("likes_count is null");
            return (Criteria) this;
        }

        public Criteria andLikesCountIsNotNull() {
            addCriterion("likes_count is not null");
            return (Criteria) this;
        }

        public Criteria andLikesCountEqualTo(Integer value) {
            addCriterion("likes_count =", value, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountNotEqualTo(Integer value) {
            addCriterion("likes_count <>", value, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountGreaterThan(Integer value) {
            addCriterion("likes_count >", value, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("likes_count >=", value, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountLessThan(Integer value) {
            addCriterion("likes_count <", value, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountLessThanOrEqualTo(Integer value) {
            addCriterion("likes_count <=", value, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountIn(List<Integer> values) {
            addCriterion("likes_count in", values, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountNotIn(List<Integer> values) {
            addCriterion("likes_count not in", values, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountBetween(Integer value1, Integer value2) {
            addCriterion("likes_count between", value1, value2, "likesCount");
            return (Criteria) this;
        }

        public Criteria andLikesCountNotBetween(Integer value1, Integer value2) {
            addCriterion("likes_count not between", value1, value2, "likesCount");
            return (Criteria) this;
        }

        public Criteria andReadCountIsNull() {
            addCriterion("read_count is null");
            return (Criteria) this;
        }

        public Criteria andReadCountIsNotNull() {
            addCriterion("read_count is not null");
            return (Criteria) this;
        }

        public Criteria andReadCountEqualTo(Integer value) {
            addCriterion("read_count =", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountNotEqualTo(Integer value) {
            addCriterion("read_count <>", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountGreaterThan(Integer value) {
            addCriterion("read_count >", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_count >=", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountLessThan(Integer value) {
            addCriterion("read_count <", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountLessThanOrEqualTo(Integer value) {
            addCriterion("read_count <=", value, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountIn(List<Integer> values) {
            addCriterion("read_count in", values, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountNotIn(List<Integer> values) {
            addCriterion("read_count not in", values, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountBetween(Integer value1, Integer value2) {
            addCriterion("read_count between", value1, value2, "readCount");
            return (Criteria) this;
        }

        public Criteria andReadCountNotBetween(Integer value1, Integer value2) {
            addCriterion("read_count not between", value1, value2, "readCount");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNull() {
            addCriterion("is_open is null");
            return (Criteria) this;
        }

        public Criteria andIsOpenIsNotNull() {
            addCriterion("is_open is not null");
            return (Criteria) this;
        }

        public Criteria andIsOpenEqualTo(Integer value) {
            addCriterion("is_open =", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotEqualTo(Integer value) {
            addCriterion("is_open <>", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThan(Integer value) {
            addCriterion("is_open >", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_open >=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThan(Integer value) {
            addCriterion("is_open <", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenLessThanOrEqualTo(Integer value) {
            addCriterion("is_open <=", value, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenIn(List<Integer> values) {
            addCriterion("is_open in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotIn(List<Integer> values) {
            addCriterion("is_open not in", values, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenBetween(Integer value1, Integer value2) {
            addCriterion("is_open between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andIsOpenNotBetween(Integer value1, Integer value2) {
            addCriterion("is_open not between", value1, value2, "isOpen");
            return (Criteria) this;
        }

        public Criteria andOnTopIsNull() {
            addCriterion("on_top is null");
            return (Criteria) this;
        }

        public Criteria andOnTopIsNotNull() {
            addCriterion("on_top is not null");
            return (Criteria) this;
        }

        public Criteria andOnTopEqualTo(Integer value) {
            addCriterion("on_top =", value, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopNotEqualTo(Integer value) {
            addCriterion("on_top <>", value, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopGreaterThan(Integer value) {
            addCriterion("on_top >", value, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopGreaterThanOrEqualTo(Integer value) {
            addCriterion("on_top >=", value, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopLessThan(Integer value) {
            addCriterion("on_top <", value, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopLessThanOrEqualTo(Integer value) {
            addCriterion("on_top <=", value, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopIn(List<Integer> values) {
            addCriterion("on_top in", values, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopNotIn(List<Integer> values) {
            addCriterion("on_top not in", values, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopBetween(Integer value1, Integer value2) {
            addCriterion("on_top between", value1, value2, "onTop");
            return (Criteria) this;
        }

        public Criteria andOnTopNotBetween(Integer value1, Integer value2) {
            addCriterion("on_top not between", value1, value2, "onTop");
            return (Criteria) this;
        }

        public Criteria andArticleFloorIsNull() {
            addCriterion("article_floor is null");
            return (Criteria) this;
        }

        public Criteria andArticleFloorIsNotNull() {
            addCriterion("article_floor is not null");
            return (Criteria) this;
        }

        public Criteria andArticleFloorEqualTo(Integer value) {
            addCriterion("article_floor =", value, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorNotEqualTo(Integer value) {
            addCriterion("article_floor <>", value, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorGreaterThan(Integer value) {
            addCriterion("article_floor >", value, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_floor >=", value, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorLessThan(Integer value) {
            addCriterion("article_floor <", value, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorLessThanOrEqualTo(Integer value) {
            addCriterion("article_floor <=", value, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorIn(List<Integer> values) {
            addCriterion("article_floor in", values, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorNotIn(List<Integer> values) {
            addCriterion("article_floor not in", values, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorBetween(Integer value1, Integer value2) {
            addCriterion("article_floor between", value1, value2, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andArticleFloorNotBetween(Integer value1, Integer value2) {
            addCriterion("article_floor not between", value1, value2, "articleFloor");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportIsNull() {
            addCriterion("author_support is null");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportIsNotNull() {
            addCriterion("author_support is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportEqualTo(Integer value) {
            addCriterion("author_support =", value, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportNotEqualTo(Integer value) {
            addCriterion("author_support <>", value, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportGreaterThan(Integer value) {
            addCriterion("author_support >", value, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportGreaterThanOrEqualTo(Integer value) {
            addCriterion("author_support >=", value, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportLessThan(Integer value) {
            addCriterion("author_support <", value, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportLessThanOrEqualTo(Integer value) {
            addCriterion("author_support <=", value, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportIn(List<Integer> values) {
            addCriterion("author_support in", values, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportNotIn(List<Integer> values) {
            addCriterion("author_support not in", values, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportBetween(Integer value1, Integer value2) {
            addCriterion("author_support between", value1, value2, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andAuthorSupportNotBetween(Integer value1, Integer value2) {
            addCriterion("author_support not between", value1, value2, "authorSupport");
            return (Criteria) this;
        }

        public Criteria andKeyWordsIsNull() {
            addCriterion("key_words is null");
            return (Criteria) this;
        }

        public Criteria andKeyWordsIsNotNull() {
            addCriterion("key_words is not null");
            return (Criteria) this;
        }

        public Criteria andKeyWordsEqualTo(String value) {
            addCriterion("key_words =", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotEqualTo(String value) {
            addCriterion("key_words <>", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsGreaterThan(String value) {
            addCriterion("key_words >", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsGreaterThanOrEqualTo(String value) {
            addCriterion("key_words >=", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsLessThan(String value) {
            addCriterion("key_words <", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsLessThanOrEqualTo(String value) {
            addCriterion("key_words <=", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsLike(String value) {
            addCriterion("key_words like", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotLike(String value) {
            addCriterion("key_words not like", value, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsIn(List<String> values) {
            addCriterion("key_words in", values, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotIn(List<String> values) {
            addCriterion("key_words not in", values, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsBetween(String value1, String value2) {
            addCriterion("key_words between", value1, value2, "keyWords");
            return (Criteria) this;
        }

        public Criteria andKeyWordsNotBetween(String value1, String value2) {
            addCriterion("key_words not between", value1, value2, "keyWords");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishIsNull() {
            addCriterion("is_content_finish is null");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishIsNotNull() {
            addCriterion("is_content_finish is not null");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishEqualTo(Integer value) {
            addCriterion("is_content_finish =", value, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishNotEqualTo(Integer value) {
            addCriterion("is_content_finish <>", value, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishGreaterThan(Integer value) {
            addCriterion("is_content_finish >", value, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_content_finish >=", value, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishLessThan(Integer value) {
            addCriterion("is_content_finish <", value, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishLessThanOrEqualTo(Integer value) {
            addCriterion("is_content_finish <=", value, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishIn(List<Integer> values) {
            addCriterion("is_content_finish in", values, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishNotIn(List<Integer> values) {
            addCriterion("is_content_finish not in", values, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishBetween(Integer value1, Integer value2) {
            addCriterion("is_content_finish between", value1, value2, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andIsContentFinishNotBetween(Integer value1, Integer value2) {
            addCriterion("is_content_finish not between", value1, value2, "isContentFinish");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hxp_article
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}