package com.pro.test.web.entity;

import java.util.Date;

public class TbHxpRefComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.ref_comment_id
     *
     * @mbggenerated
     */
    private String refCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.comment_id
     *
     * @mbggenerated
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.ref_comment_context
     *
     * @mbggenerated
     */
    private String refCommentContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.user_head_portrait
     *
     * @mbggenerated
     */
    private String userHeadPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.to_user_name
     *
     * @mbggenerated
     */
    private String toUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.to_user_id
     *
     * @mbggenerated
     */
    private String toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.ref_comment_ip
     *
     * @mbggenerated
     */
    private String refCommentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_ref_comment.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public TbHxpRefComment(String refCommentId, String articleId, String commentId, String refCommentContext, String userId, String userName, String userHeadPortrait, String toUserName, String toUserId, String refCommentIp, Date createDate) {
        this.refCommentId = refCommentId;
        this.articleId = articleId;
        this.commentId = commentId;
        this.refCommentContext = refCommentContext;
        this.userId = userId;
        this.userName = userName;
        this.userHeadPortrait = userHeadPortrait;
        this.toUserName = toUserName;
        this.toUserId = toUserId;
        this.refCommentIp = refCommentIp;
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.ref_comment_id
     *
     * @return the value of tb_hxp_ref_comment.ref_comment_id
     *
     * @mbggenerated
     */
    public String getRefCommentId() {
        return refCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.article_id
     *
     * @return the value of tb_hxp_ref_comment.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.comment_id
     *
     * @return the value of tb_hxp_ref_comment.comment_id
     *
     * @mbggenerated
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.ref_comment_context
     *
     * @return the value of tb_hxp_ref_comment.ref_comment_context
     *
     * @mbggenerated
     */
    public String getRefCommentContext() {
        return refCommentContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.user_id
     *
     * @return the value of tb_hxp_ref_comment.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.user_name
     *
     * @return the value of tb_hxp_ref_comment.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.user_head_portrait
     *
     * @return the value of tb_hxp_ref_comment.user_head_portrait
     *
     * @mbggenerated
     */
    public String getUserHeadPortrait() {
        return userHeadPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.to_user_name
     *
     * @return the value of tb_hxp_ref_comment.to_user_name
     *
     * @mbggenerated
     */
    public String getToUserName() {
        return toUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.to_user_id
     *
     * @return the value of tb_hxp_ref_comment.to_user_id
     *
     * @mbggenerated
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.ref_comment_ip
     *
     * @return the value of tb_hxp_ref_comment.ref_comment_ip
     *
     * @mbggenerated
     */
    public String getRefCommentIp() {
        return refCommentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_ref_comment.create_date
     *
     * @return the value of tb_hxp_ref_comment.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }
}