package com.pro.test.web.entity;

import java.util.Date;

public class TbHxpArticleContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article_content.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article_content.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article_content.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article_content.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article_content.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article_content.article_content
     *
     * @mbggenerated
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article_content
     *
     * @mbggenerated
     */
    public TbHxpArticleContent(String articleId, Date createDate, String createBy, Date updateDate, String updateBy, String articleContent) {
        this.articleId = articleId;
        this.createDate = createDate;
        this.createBy = createBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.articleContent = articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article_content.article_id
     *
     * @return the value of tb_hxp_article_content.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article_content.create_date
     *
     * @return the value of tb_hxp_article_content.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article_content.create_by
     *
     * @return the value of tb_hxp_article_content.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article_content.update_date
     *
     * @return the value of tb_hxp_article_content.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article_content.update_by
     *
     * @return the value of tb_hxp_article_content.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article_content.article_content
     *
     * @return the value of tb_hxp_article_content.article_content
     *
     * @mbggenerated
     */
    public String getArticleContent() {
        return articleContent;
    }
}