package com.pro.test.web.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TbHxpRefCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public TbHxpRefCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andRefCommentIdIsNull() {
            addCriterion("ref_comment_id is null");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdIsNotNull() {
            addCriterion("ref_comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdEqualTo(String value) {
            addCriterion("ref_comment_id =", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdNotEqualTo(String value) {
            addCriterion("ref_comment_id <>", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdGreaterThan(String value) {
            addCriterion("ref_comment_id >", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdGreaterThanOrEqualTo(String value) {
            addCriterion("ref_comment_id >=", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdLessThan(String value) {
            addCriterion("ref_comment_id <", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdLessThanOrEqualTo(String value) {
            addCriterion("ref_comment_id <=", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdLike(String value) {
            addCriterion("ref_comment_id like", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdNotLike(String value) {
            addCriterion("ref_comment_id not like", value, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdIn(List<String> values) {
            addCriterion("ref_comment_id in", values, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdNotIn(List<String> values) {
            addCriterion("ref_comment_id not in", values, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdBetween(String value1, String value2) {
            addCriterion("ref_comment_id between", value1, value2, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIdNotBetween(String value1, String value2) {
            addCriterion("ref_comment_id not between", value1, value2, "refCommentId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("article_id is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("article_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(String value) {
            addCriterion("article_id =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(String value) {
            addCriterion("article_id <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(String value) {
            addCriterion("article_id >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(String value) {
            addCriterion("article_id >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(String value) {
            addCriterion("article_id <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(String value) {
            addCriterion("article_id <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLike(String value) {
            addCriterion("article_id like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotLike(String value) {
            addCriterion("article_id not like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<String> values) {
            addCriterion("article_id in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<String> values) {
            addCriterion("article_id not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(String value1, String value2) {
            addCriterion("article_id between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(String value1, String value2) {
            addCriterion("article_id not between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(String value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(String value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(String value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(String value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(String value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(String value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLike(String value) {
            addCriterion("comment_id like", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotLike(String value) {
            addCriterion("comment_id not like", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<String> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<String> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(String value1, String value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(String value1, String value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextIsNull() {
            addCriterion("ref_comment_context is null");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextIsNotNull() {
            addCriterion("ref_comment_context is not null");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextEqualTo(String value) {
            addCriterion("ref_comment_context =", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextNotEqualTo(String value) {
            addCriterion("ref_comment_context <>", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextGreaterThan(String value) {
            addCriterion("ref_comment_context >", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextGreaterThanOrEqualTo(String value) {
            addCriterion("ref_comment_context >=", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextLessThan(String value) {
            addCriterion("ref_comment_context <", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextLessThanOrEqualTo(String value) {
            addCriterion("ref_comment_context <=", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextLike(String value) {
            addCriterion("ref_comment_context like", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextNotLike(String value) {
            addCriterion("ref_comment_context not like", value, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextIn(List<String> values) {
            addCriterion("ref_comment_context in", values, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextNotIn(List<String> values) {
            addCriterion("ref_comment_context not in", values, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextBetween(String value1, String value2) {
            addCriterion("ref_comment_context between", value1, value2, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andRefCommentContextNotBetween(String value1, String value2) {
            addCriterion("ref_comment_context not between", value1, value2, "refCommentContext");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitIsNull() {
            addCriterion("user_head_portrait is null");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitIsNotNull() {
            addCriterion("user_head_portrait is not null");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitEqualTo(String value) {
            addCriterion("user_head_portrait =", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitNotEqualTo(String value) {
            addCriterion("user_head_portrait <>", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitGreaterThan(String value) {
            addCriterion("user_head_portrait >", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitGreaterThanOrEqualTo(String value) {
            addCriterion("user_head_portrait >=", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitLessThan(String value) {
            addCriterion("user_head_portrait <", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitLessThanOrEqualTo(String value) {
            addCriterion("user_head_portrait <=", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitLike(String value) {
            addCriterion("user_head_portrait like", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitNotLike(String value) {
            addCriterion("user_head_portrait not like", value, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitIn(List<String> values) {
            addCriterion("user_head_portrait in", values, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitNotIn(List<String> values) {
            addCriterion("user_head_portrait not in", values, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitBetween(String value1, String value2) {
            addCriterion("user_head_portrait between", value1, value2, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andUserHeadPortraitNotBetween(String value1, String value2) {
            addCriterion("user_head_portrait not between", value1, value2, "userHeadPortrait");
            return (Criteria) this;
        }

        public Criteria andToUserNameIsNull() {
            addCriterion("to_user_name is null");
            return (Criteria) this;
        }

        public Criteria andToUserNameIsNotNull() {
            addCriterion("to_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andToUserNameEqualTo(String value) {
            addCriterion("to_user_name =", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameNotEqualTo(String value) {
            addCriterion("to_user_name <>", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameGreaterThan(String value) {
            addCriterion("to_user_name >", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("to_user_name >=", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameLessThan(String value) {
            addCriterion("to_user_name <", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameLessThanOrEqualTo(String value) {
            addCriterion("to_user_name <=", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameLike(String value) {
            addCriterion("to_user_name like", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameNotLike(String value) {
            addCriterion("to_user_name not like", value, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameIn(List<String> values) {
            addCriterion("to_user_name in", values, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameNotIn(List<String> values) {
            addCriterion("to_user_name not in", values, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameBetween(String value1, String value2) {
            addCriterion("to_user_name between", value1, value2, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserNameNotBetween(String value1, String value2) {
            addCriterion("to_user_name not between", value1, value2, "toUserName");
            return (Criteria) this;
        }

        public Criteria andToUserIdIsNull() {
            addCriterion("to_user_id is null");
            return (Criteria) this;
        }

        public Criteria andToUserIdIsNotNull() {
            addCriterion("to_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andToUserIdEqualTo(String value) {
            addCriterion("to_user_id =", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdNotEqualTo(String value) {
            addCriterion("to_user_id <>", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdGreaterThan(String value) {
            addCriterion("to_user_id >", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("to_user_id >=", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdLessThan(String value) {
            addCriterion("to_user_id <", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdLessThanOrEqualTo(String value) {
            addCriterion("to_user_id <=", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdLike(String value) {
            addCriterion("to_user_id like", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdNotLike(String value) {
            addCriterion("to_user_id not like", value, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdIn(List<String> values) {
            addCriterion("to_user_id in", values, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdNotIn(List<String> values) {
            addCriterion("to_user_id not in", values, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdBetween(String value1, String value2) {
            addCriterion("to_user_id between", value1, value2, "toUserId");
            return (Criteria) this;
        }

        public Criteria andToUserIdNotBetween(String value1, String value2) {
            addCriterion("to_user_id not between", value1, value2, "toUserId");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpIsNull() {
            addCriterion("ref_comment_ip is null");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpIsNotNull() {
            addCriterion("ref_comment_ip is not null");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpEqualTo(String value) {
            addCriterion("ref_comment_ip =", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpNotEqualTo(String value) {
            addCriterion("ref_comment_ip <>", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpGreaterThan(String value) {
            addCriterion("ref_comment_ip >", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpGreaterThanOrEqualTo(String value) {
            addCriterion("ref_comment_ip >=", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpLessThan(String value) {
            addCriterion("ref_comment_ip <", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpLessThanOrEqualTo(String value) {
            addCriterion("ref_comment_ip <=", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpLike(String value) {
            addCriterion("ref_comment_ip like", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpNotLike(String value) {
            addCriterion("ref_comment_ip not like", value, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpIn(List<String> values) {
            addCriterion("ref_comment_ip in", values, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpNotIn(List<String> values) {
            addCriterion("ref_comment_ip not in", values, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpBetween(String value1, String value2) {
            addCriterion("ref_comment_ip between", value1, value2, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andRefCommentIpNotBetween(String value1, String value2) {
            addCriterion("ref_comment_ip not between", value1, value2, "refCommentIp");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterionForJDBCDate("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterionForJDBCDate("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterionForJDBCDate("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_hxp_ref_comment
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}