package com.pro.test.web.entity;

import java.util.Date;

public class TbHxpUserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.login_password
     *
     * @mbggenerated
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.login_count
     *
     * @mbggenerated
     */
    private Integer loginCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.is_locked
     *
     * @mbggenerated
     */
    private Integer isLocked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.unlocked_date
     *
     * @mbggenerated
     */
    private Date unlockedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.last_login_time
     *
     * @mbggenerated
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_user_login.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_user_login
     *
     * @mbggenerated
     */
    public TbHxpUserLogin(String id, String loginName, String loginPassword, String userId, Integer loginCount, Integer isLocked, Date unlockedDate, String ipAddress, Date lastLoginTime, Integer status) {
        this.id = id;
        this.loginName = loginName;
        this.loginPassword = loginPassword;
        this.userId = userId;
        this.loginCount = loginCount;
        this.isLocked = isLocked;
        this.unlockedDate = unlockedDate;
        this.ipAddress = ipAddress;
        this.lastLoginTime = lastLoginTime;
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.id
     *
     * @return the value of tb_hxp_user_login.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.login_name
     *
     * @return the value of tb_hxp_user_login.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.login_password
     *
     * @return the value of tb_hxp_user_login.login_password
     *
     * @mbggenerated
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.user_id
     *
     * @return the value of tb_hxp_user_login.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.login_count
     *
     * @return the value of tb_hxp_user_login.login_count
     *
     * @mbggenerated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.is_locked
     *
     * @return the value of tb_hxp_user_login.is_locked
     *
     * @mbggenerated
     */
    public Integer getIsLocked() {
        return isLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.unlocked_date
     *
     * @return the value of tb_hxp_user_login.unlocked_date
     *
     * @mbggenerated
     */
    public Date getUnlockedDate() {
        return unlockedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.ip_address
     *
     * @return the value of tb_hxp_user_login.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.last_login_time
     *
     * @return the value of tb_hxp_user_login.last_login_time
     *
     * @mbggenerated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_user_login.status
     *
     * @return the value of tb_hxp_user_login.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }
}