package com.pro.test.web.entity;

import java.util.Date;

public class TbHxpArticle {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_id
     *
     * @mbggenerated
     */
    private String articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_title
     *
     * @mbggenerated
     */
    private String articleTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_introduced
     *
     * @mbggenerated
     */
    private String articleIntroduced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_author_id
     *
     * @mbggenerated
     */
    private String articleAuthorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_author_name
     *
     * @mbggenerated
     */
    private String articleAuthorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_tags
     *
     * @mbggenerated
     */
    private String articleTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.last_comment_date
     *
     * @mbggenerated
     */
    private Date lastCommentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.comment_count
     *
     * @mbggenerated
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.likes_count
     *
     * @mbggenerated
     */
    private Integer likesCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.read_count
     *
     * @mbggenerated
     */
    private Integer readCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.is_open
     *
     * @mbggenerated
     */
    private Integer isOpen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.on_top
     *
     * @mbggenerated
     */
    private Integer onTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.article_floor
     *
     * @mbggenerated
     */
    private Integer articleFloor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.author_support
     *
     * @mbggenerated
     */
    private Integer authorSupport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.key_words
     *
     * @mbggenerated
     */
    private String keyWords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.is_content_finish
     *
     * @mbggenerated
     */
    private Integer isContentFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.update_date
     *
     * @mbggenerated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_hxp_article.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_hxp_article
     *
     * @mbggenerated
     */
    public TbHxpArticle(String articleId, String articleTitle, String articleIntroduced, String articleAuthorId, String articleAuthorName, String articleTags, Date lastCommentDate, Integer commentCount, Integer likesCount, Integer readCount, Integer isOpen, Integer onTop, Integer articleFloor, Integer authorSupport, String keyWords, Integer isContentFinish, Date createDate, String createBy, Date updateDate, String updateBy, String remark) {
        this.articleId = articleId;
        this.articleTitle = articleTitle;
        this.articleIntroduced = articleIntroduced;
        this.articleAuthorId = articleAuthorId;
        this.articleAuthorName = articleAuthorName;
        this.articleTags = articleTags;
        this.lastCommentDate = lastCommentDate;
        this.commentCount = commentCount;
        this.likesCount = likesCount;
        this.readCount = readCount;
        this.isOpen = isOpen;
        this.onTop = onTop;
        this.articleFloor = articleFloor;
        this.authorSupport = authorSupport;
        this.keyWords = keyWords;
        this.isContentFinish = isContentFinish;
        this.createDate = createDate;
        this.createBy = createBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_id
     *
     * @return the value of tb_hxp_article.article_id
     *
     * @mbggenerated
     */
    public String getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_title
     *
     * @return the value of tb_hxp_article.article_title
     *
     * @mbggenerated
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_introduced
     *
     * @return the value of tb_hxp_article.article_introduced
     *
     * @mbggenerated
     */
    public String getArticleIntroduced() {
        return articleIntroduced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_author_id
     *
     * @return the value of tb_hxp_article.article_author_id
     *
     * @mbggenerated
     */
    public String getArticleAuthorId() {
        return articleAuthorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_author_name
     *
     * @return the value of tb_hxp_article.article_author_name
     *
     * @mbggenerated
     */
    public String getArticleAuthorName() {
        return articleAuthorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_tags
     *
     * @return the value of tb_hxp_article.article_tags
     *
     * @mbggenerated
     */
    public String getArticleTags() {
        return articleTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.last_comment_date
     *
     * @return the value of tb_hxp_article.last_comment_date
     *
     * @mbggenerated
     */
    public Date getLastCommentDate() {
        return lastCommentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.comment_count
     *
     * @return the value of tb_hxp_article.comment_count
     *
     * @mbggenerated
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.likes_count
     *
     * @return the value of tb_hxp_article.likes_count
     *
     * @mbggenerated
     */
    public Integer getLikesCount() {
        return likesCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.read_count
     *
     * @return the value of tb_hxp_article.read_count
     *
     * @mbggenerated
     */
    public Integer getReadCount() {
        return readCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.is_open
     *
     * @return the value of tb_hxp_article.is_open
     *
     * @mbggenerated
     */
    public Integer getIsOpen() {
        return isOpen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.on_top
     *
     * @return the value of tb_hxp_article.on_top
     *
     * @mbggenerated
     */
    public Integer getOnTop() {
        return onTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.article_floor
     *
     * @return the value of tb_hxp_article.article_floor
     *
     * @mbggenerated
     */
    public Integer getArticleFloor() {
        return articleFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.author_support
     *
     * @return the value of tb_hxp_article.author_support
     *
     * @mbggenerated
     */
    public Integer getAuthorSupport() {
        return authorSupport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.key_words
     *
     * @return the value of tb_hxp_article.key_words
     *
     * @mbggenerated
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.is_content_finish
     *
     * @return the value of tb_hxp_article.is_content_finish
     *
     * @mbggenerated
     */
    public Integer getIsContentFinish() {
        return isContentFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.create_date
     *
     * @return the value of tb_hxp_article.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.create_by
     *
     * @return the value of tb_hxp_article.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.update_date
     *
     * @return the value of tb_hxp_article.update_date
     *
     * @mbggenerated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.update_by
     *
     * @return the value of tb_hxp_article.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_hxp_article.remark
     *
     * @return the value of tb_hxp_article.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }
}